### ISSUE TITLE
Invoke real real or coginito authorizer

### ISSUE THREAD

**Issue by gertjvr** [gertjvr/serverless-docker#2]
# This is a Feature Proposal

## Description
`serverless` allows us to configure an [API Gateway]() authorizer by referencing the methodArn this feature will allow us to execute a common authorizer a cross other deployed services. No need to redeploy a custom authorizer per service.

```yml
lists:
    handler: functions/index.handler
    events: 
      - http:
          path: lists
          method: POST
          authorizer: arn:aws:execute-api:{region}:{accountId}:{restApi}/${stage}/${method}{path}
``` 

Similar or dependent issues:
* None

## Additional Data

* None
